package App.model.response;

public enum ResponseStatus {
    AUTHORIZATION_ALREADY_GRANTED,
    AUTHORIZATION_CODE_NOT_FOUND,
    AUTHORIZATION_CODE_RECEIVED,
    AUTHORIZATION_GRANTED,
    AUTHORIZATION_REQUIRED,
    AUTHORIZATION_TOKENS_NOT_FOUND,
    CATEGORY_LIST_REQUIRED,
    CONNECTION_PROBLEM,
    OBJECTS_RECEIVED,
    RECEIVED_ERROR_API_RESPONSE,
    UNKNOWN_CATEGORY_REQUESTED,
}
